[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sorting_package_Neerajk4"
version = "0.1.0"
description = "A brief test in creating packages in python in order to test out"
readme = "README.md"
dependencies = [
    "requests",
]